[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "flooride"
version = "1.1.0"
description = "light weight & low level ai framework"
authors = [{name = "joemamasofat676767", email = "joemamasofat676767@gmail.com"}]
readme = "README.md"
license = "MIT"
