[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "flooride"
version = "0.1.15"
description = "light weight & low level ai framework"
authors = [{name = "blanco", email = "joemamasofat676767@gmail.com"}]
readme = "README.md"
license = "MIT"
